version: '3.9'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-network
    restart: always

  redis:
    image: redis:alpine
    networks:
      - django-network
    restart: always
    

  web:
    image: omkardevabattula/django-channels-redis
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "9876:8000"
    networks:
      - django-network
    restart: always
    

volumes:
  postgres_data:

networks:
  django-network:
